### ISSUE TITLE
Enable travis-ci on this repo?

### ISSUE THREAD

**Issue by javierbertoli** [saltstack-formulas/bareos-formula#1]
@aboe76, is there any chance to enable the travis-ci hook on this repo? Should I use my own travis credentials? Sorry to bother you, but I don't know which is the usual procedure regarding it for the saltstack formulas

**Comment by blbradley** [comment]
Hello @javierbertoli 

Since you created this repo and are part of the org, you can turn Travis on yourself for this repo.

Good luck!

**Comment by aboe76** [comment]
@javierbertoli I don't have the credentials,

**Comment by javierbertoli** [comment]
@aboe76, neither do I. @blbradley I can enable travis on the repo, however, the GH page to enable it asks for the travis-ci credentials of the account to which associate the repo. I have my own (I'm OK using them if no 'saltstack-formulas' org ones are available), but I think there are and it makes sense to associate the repo (and travis tests) to the org rather than to myself, right?

**Comment by aboe76** [comment]
@nmadhok can you enable this?

**Comment by blbradley** [comment]
@javierbertoli The integrations page in repo settings is a new since I did this myself to `metricbeat-formula`. My user is set on that one.
